[project]
name = "BTC-Time-Capsule"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/BTC-Time-Capsule/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.BTC-Time-Capsule]
path = "contracts/BTC-Time-Capsule.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
